use wasm_bindgen::prelude::*;
use serde::{Serialize, Deserialize};

#[wasm_bindgen]
#[derive(strum_macros::Display, Deserialize, Serialize)]
pub enum ContextTypes {
    Unexpected,
    Space,
    Identifier,
    AsStatement,
    // *
    Asterix,
    IdentifierAsStatement,
    // Identifier separated by a coma
    IdentifierList,
    IdentifierSemiColonList,
    // @
    At,
    SemiColon,
    Coma,
    DoublePoint,
    Point,
    MultipleSpaces,
    LineBreak,
    StringSingleQuote,
    StringDoubleQuote,
    StringTemplateQuote,
    StringTemplateQuoteEval,
    Comment,
    CommentBlock,
    Braces,
    CurlyBrackets,
    Array,
    Parenthese,
    Argument,
    // COMPONENT
    ComponentTypeStatement,
    ComponentDeclaration,
    // HTML
    HTMLComment,
    ImportAmbient,
    ImportStatement,
    ExportStatement,
    ImportComponentStatement,
    ImportStatementFrom,
    ImportAllAlias,
    InjectAmbient,
    TextNode,
    Node,
    NodeOpening,
    NodeOpeningEnd,
    NodeClosing,
    NodeClosingEnd,
    Flag,
    FlagStruct,
    FlagSpread,
    Attribute,
    AttributeModifier,
    AttributeModifierType,
    AttributeProperty,
    AttributeBoolean,
    AttributeValueQuoteSingle,
    AttributeValueQuoteDouble,
    AttributeValueQuoteTemplate,
    AttributeValueCurlyBrackets,
    AttributeValueUnquoted,
    AttributeValueBraces,
    AttributeValueArray,
    AttributeValueContent,
    AttributeValueStart,
    AttributeValueEnd,
    /**
     * all contexts involved into protocol
     */
    Protocol,
    /**
     * all contexts involved into stylesheet
     */
    StyleSheet,
    StyleSheetEnd,
    StyleSheetRule,
    StyleSheetAtRule,
    StyleSheetAtRuleCharset,
    StyleSheetTypeAssignment,
    StyleSheetAtRuleConst,
    StyleSheetAtRuleConstType,
    StyleSheetAtRuleConstEqual,
    StyleSheetAtRuleConstValue,
    StyleSheetAtRuleExport,
    StyleSheetType,
    StyleSheetCurlyBrackets,
    StyleSheetRuleSpread,
    StyleSheetParentRef,
    StyleSheetPropertyList,
    StyleSheetProperty,
    StyleSheetPropertyValue,
    StyleSheetPseudoProperty,
    StyleSheetPseudoPropertyName,
    StyleSheetPseudoPropertyParentheses,
    StyleSheetPseudoPropertyItem,
    StyleSheetPseudoPropertyItemName,
    StyleSheetPseudoPropertyItemValue,
    StyleSheetSelector,
    StyleSheetSelectorList,
    StyleSheetSelectorHTMLElement,
    StyleSheetSelectorClass,
    StyleSheetSelectorId,
    StyleSheetSelectorAttribute,
    StyleSheetSelectorAttributeEqual,
    StyleSheetSelectorAttributeValue,
    StyleSheetSelectorPseudoClass,
    StyleSheetSelectorPseudoElement,
    StyleSheetSelectorCombinatorChildSelector,
    StyleSheetSelectorCombinatorAdjacentSibling,
    StyleSheetSelectorCombinatorGeneralSibling,
    StyleSheetSelectorCombinatorAll,
    StyleSheetHexType,
    StyleSheetPixelType,
    StyleSheetAtRuleTrait,
}

#[derive(strum_macros::Display, Deserialize, Serialize)]
pub enum Reason {
    Unsupported = 0,
    None = 3,
    UnexpectedToken = 1436,
    HTMLTagNotClosed = 1443,
    CommentBlockOpen = 1519,
    StringSingleQuoteOpen = 1593,
    StringDoubleQuoteOpen = 1633,
    StringTemplateQuoteOpen = 1678,
    StringTemplateQuoteEvaluationOpen = 1725,
    BracesOpen = 1773,
    CurlyBracketsOpen = 1819,
    ArrayOpen = 1866,
    ParentheseOpen = 1896,
    HTMLClosingTagWithoutOpening = 2116,
    HTMLTagNotFinish = 2128,
    HTMLCommentOpen = 2211,
    ImportAmbientStringMissing = 2274,
    ImportStatementNotFinish = 2354,
    OgoneFlagNotFinish = 2406,
    OgoneSpreadFlagNotClosed = 2491,
    HTMLAttributeNotClosed = 2549,
    HTMLBooleanAttributeNotClosed = 2590,
    HTMLAttributeNameNotClosed = 2630,
    HTMLAttributeValueUnquotedNotClosed = 2670,
    StyleSheetAtRuleCharsetInvalid = 2887,
    StyleSheetAtRuleCharsetStringIsMissing = 2890,
    StyleSheetAtRuleCharsetNotFinish = 2894,
    StyleSheetAtRuleCurlyBracketsAreMissing = 2960,
    StyleSheetTypeAssignmentNotFinish = 3004,
    StyleSheetAttributeNotClosed = 3408,
    StyleSheetPropertyListOpen = 3533,
    StyleSheetRulePropertyValueNotClosed = 3764,
    StyleSheetRuleSpreadNameMissing = 3923,
    ComponentDeclarationNodeMissing = 4200,
    ModifierNotFinished = 4300,
    AsStatementMissingIdentifier = 4301,
    ComponentNotFound = 5000,
}
